sudo: false
language: node_js
before_script: scripts/prebuild.sh
node_js:
- '6.1'
- '6.0'
- '5.0'
- '4.1'
- '4.0'
before_deploy: scripts/before_deploy.sh
deploy:
  api_key:
    secure: 
  on:
    repo: TRex22/BorrowMyBooks
    branch: master
  email: contact@jasonchalom.com
  provider: npm